---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: weblogic-operator
---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: weblogic-operator
#  namespace: weblogic-operator
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weblogic-operator
#  namespace: weblogic-operator
  labels:
    app: weblogic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weblogic-operator
  template:
    metadata:
      labels:
        app: weblogic-operator
    spec:
#      serviceAccountName: weblogic-operator
      imagePullSecrets:
      - name: gcr-secret
      volumes:
      - name: weblogic-operator-storage
        persistentVolumeClaim:
          claimName: weblogic-operator-claim
      containers:
      - name: weblogic-operator-controller
        imagePullPolicy: IfNotPresent
        image: gcr.io/fmwplt-gcp/weblogic-operator:1710300221
        volumeMounts:
        - mountPath: "/u01/oracle/user_projects"
          name: weblogic-operator-storage
        ports:
        - containerPort: 9999
        args:
          - --v=4
          - --alsologtostderr=true
